index:
    path: /
    controller: App\Controller\HomeController::index

about:
    path: /about
    controller: App\Controller\AboutController::about

lui:
    path: /lui
    controller: App\Controller\PourLuiController::pourLui

elle:
    path: /elle
    controller: App\Controller\PourElleController::pourElle


contact:
    path: /contact
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    methods: [GET]
    defaults:
        template: contact/contact.html.twig

post-contact:
    path: /contact
    controller: App\Controller\ContactController::index
    methods: [POST]


ficheProduit:
    path: /ficheProduit
    controller: App\Controller\FicheProduitController::ficheProduit


