# admin:
#     path: /admin
#     controller: App\Controller\AdminController::admin


index:
    path: /
    controller: App\Controller\HomeController::index

about:
    path: /about
    controller: App\Controller\AboutController::about

lui:
    path: /lui
    controller: App\Controller\PourLuiController::pourLui

elle:
    path: /elle
    controller: App\Controller\PourElleController::pourElle


login:
    path: /login
    controller: App\Controller\HomeController::index

logout:
    path: /logout
    controller: App\Controller\LoginController::logout 
  

register:
    path: /register
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    methods: [GET]
    defaults:
        template: base.html.twig

postregister:
    path: /register
    controller: App\Controller\LoginController::postregister    
    methods: [POST]
    
contact:
    path: /contact
    controller: App\Controller\ContactController::index
    methods: [GET]

post-contact:
    path: /contact
    controller: App\Controller\ContactController::index
    methods: [POST]    
   
