index:
    path: /
    controller: App\Controller\HomeController::index

about:
    path: /about
    controller: App\Controller\AboutController::about

elle:
    path: /elle
    controller: App\Controller\PourElleController::pourElle

contact:
    path: /contact
    controller: App\Controller\ContactController::contact